// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OlympicGames.Models;

namespace OlympicGames.Migrations
{
    [DbContext(typeof(CountryContext))]
    [Migration("20220308183633_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OlympicGames.Models.Country", b =>
                {
                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FlagImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CountryId");

                    b.HasIndex("GameId");

                    b.HasIndex("SportId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = "ca",
                            FlagImage = "ca.png",
                            GameId = "wo",
                            Name = "Canada",
                            SportId = "curl"
                        },
                        new
                        {
                            CountryId = "se",
                            FlagImage = "se.png",
                            GameId = "wo",
                            Name = "Sweden",
                            SportId = "curl"
                        },
                        new
                        {
                            CountryId = "gb",
                            FlagImage = "gb.png",
                            GameId = "wo",
                            Name = "Great Britain",
                            SportId = "curl"
                        },
                        new
                        {
                            CountryId = "jm",
                            FlagImage = "jm.png",
                            GameId = "wo",
                            Name = "Jamaica",
                            SportId = "bob"
                        },
                        new
                        {
                            CountryId = "it",
                            FlagImage = "it.png",
                            GameId = "wo",
                            Name = "Italy",
                            SportId = "bob"
                        },
                        new
                        {
                            CountryId = "jp",
                            FlagImage = "jp.png",
                            GameId = "wo",
                            Name = "Japan",
                            SportId = "bob"
                        },
                        new
                        {
                            CountryId = "germany",
                            FlagImage = "germany.png",
                            GameId = "so",
                            Name = "Germany",
                            SportId = "dive"
                        },
                        new
                        {
                            CountryId = "china",
                            FlagImage = "china.png",
                            GameId = "so",
                            Name = "China",
                            SportId = "dive"
                        },
                        new
                        {
                            CountryId = "mx",
                            FlagImage = "mx.png",
                            GameId = "so",
                            Name = "Mexico",
                            SportId = "dive"
                        },
                        new
                        {
                            CountryId = "br",
                            FlagImage = "br.png",
                            GameId = "so",
                            Name = "Brazil",
                            SportId = "rc"
                        },
                        new
                        {
                            CountryId = "bl",
                            FlagImage = "nl.png",
                            GameId = "so",
                            Name = "Netherlands",
                            SportId = "rc"
                        },
                        new
                        {
                            CountryId = "us",
                            FlagImage = "us.png",
                            GameId = "so",
                            Name = "USA",
                            SportId = "rc"
                        },
                        new
                        {
                            CountryId = "th",
                            FlagImage = "th.png",
                            GameId = "pa",
                            Name = "Thailand",
                            SportId = "arch"
                        },
                        new
                        {
                            CountryId = "uy",
                            FlagImage = "uy.png",
                            GameId = "pa",
                            Name = "Uruguay",
                            SportId = "arch"
                        },
                        new
                        {
                            CountryId = "ua",
                            FlagImage = "ua.png",
                            GameId = "pa",
                            Name = "Ukraine",
                            SportId = "arch"
                        },
                        new
                        {
                            CountryId = "austria",
                            FlagImage = "austria.png",
                            GameId = "pa",
                            Name = "Austria",
                            SportId = "cs"
                        },
                        new
                        {
                            CountryId = "pk",
                            FlagImage = "pk.png",
                            GameId = "pa",
                            Name = "Pakistan",
                            SportId = "cs"
                        },
                        new
                        {
                            CountryId = "zw",
                            FlagImage = "zw.png",
                            GameId = "pa",
                            Name = "Zimbabwe",
                            SportId = "cs"
                        },
                        new
                        {
                            CountryId = "fr",
                            FlagImage = "fr.png",
                            GameId = "yo",
                            Name = "France",
                            SportId = "bd"
                        },
                        new
                        {
                            CountryId = "cy",
                            FlagImage = "cy.png",
                            GameId = "yo",
                            Name = "Cyprus",
                            SportId = "bd"
                        },
                        new
                        {
                            CountryId = "ru",
                            FlagImage = "ru.png",
                            GameId = "yo",
                            Name = "Russia",
                            SportId = "bd"
                        },
                        new
                        {
                            CountryId = "fi",
                            FlagImage = "fi.png",
                            GameId = "yo",
                            Name = "Finland",
                            SportId = "sb"
                        },
                        new
                        {
                            CountryId = "sk",
                            FlagImage = "sk.png",
                            GameId = "yo",
                            Name = "Slovakia",
                            SportId = "sb"
                        },
                        new
                        {
                            CountryId = "pt",
                            FlagImage = "pt.png",
                            GameId = "yo",
                            Name = "Portugal",
                            SportId = "sb"
                        });
                });

            modelBuilder.Entity("OlympicGames.Models.Game", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = "wo",
                            Name = "Winter Olympics"
                        },
                        new
                        {
                            GameId = "so",
                            Name = "Summer Olympics"
                        },
                        new
                        {
                            GameId = "pa",
                            Name = "Paralympics"
                        },
                        new
                        {
                            GameId = "yo",
                            Name = "Youth Olympics"
                        });
                });

            modelBuilder.Entity("OlympicGames.Models.Sport", b =>
                {
                    b.Property<string>("SportId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportId");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            SportId = "curl",
                            Name = "Curling"
                        },
                        new
                        {
                            SportId = "bob",
                            Name = "Bobsleigh"
                        },
                        new
                        {
                            SportId = "dive",
                            Name = "Diving"
                        },
                        new
                        {
                            SportId = "rc",
                            Name = "Road Cycling"
                        },
                        new
                        {
                            SportId = "arch",
                            Name = "Archery"
                        },
                        new
                        {
                            SportId = "cs",
                            Name = "Canoe Spring"
                        },
                        new
                        {
                            SportId = "bd",
                            Name = "Break Dancing"
                        },
                        new
                        {
                            SportId = "sb",
                            Name = "Skateboarding"
                        });
                });

            modelBuilder.Entity("OlympicGames.Models.Country", b =>
                {
                    b.HasOne("OlympicGames.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId");

                    b.HasOne("OlympicGames.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId");
                });
#pragma warning restore 612, 618
        }
    }
}
